// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4BEKKMGARCH_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CCCMGARCH_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4DCCMGARCH_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4forecastBEKK_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4forecastCCC_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4forecastDCC_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4pdBEKKMGARCH_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4BEKKMGARCH_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BEKKMGARCH_mod, 0},
    {"_rcpp_module_boot_stan_fit4CCCMGARCH_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CCCMGARCH_mod, 0},
    {"_rcpp_module_boot_stan_fit4DCCMGARCH_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4DCCMGARCH_mod, 0},
    {"_rcpp_module_boot_stan_fit4forecastBEKK_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4forecastBEKK_mod, 0},
    {"_rcpp_module_boot_stan_fit4forecastCCC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4forecastCCC_mod, 0},
    {"_rcpp_module_boot_stan_fit4forecastDCC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4forecastDCC_mod, 0},
    {"_rcpp_module_boot_stan_fit4pdBEKKMGARCH_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4pdBEKKMGARCH_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bmgarch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
